# Generated by Django 4.2.11 on 2024-03-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_diary_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='image',
            new_name='picture',
        ),
    ]
